# OptiFit 2.0 Backend Integration Test Suite
import os
import unittest
import json
import sqlite3
import io
from PIL import Image

# Add root folder to sys.path so we can run test directly
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from backend.app import app
from backend.database.db import DB_PATH

class OptiFitBackendTestCase(unittest.TestCase):
    def setUp(self):
        """Set up test client and clear any leftover test user."""
        self.app = app.test_client()
        self.app.testing = True
        
        # Test accounts email
        self.test_email = "tester_optifit_99@example.com"
        self.test_admin_email = "tester_admin_99@example.com"
        
        self.cleanup_users()

    def tearDown(self):
        """Cleanup test records after runs."""
        self.cleanup_users()

    def cleanup_users(self):
        """Helper to remove any database records generated by tests."""
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        
        # Find user IDs
        cursor.execute("SELECT id FROM users WHERE email IN (?, ?)", (self.test_email, self.test_admin_email))
        user_ids = [row[0] for row in cursor.fetchall()]
        
        for uid in user_ids:
            # Cascading deletes should handle references but let's be explicit
            cursor.execute("DELETE FROM user_preferences WHERE user_id = ?", (uid,))
            cursor.execute("DELETE FROM wardrobe WHERE user_id = ?", (uid,))
            cursor.execute("DELETE FROM recommendations WHERE user_id = ?", (uid,))
            cursor.execute("DELETE FROM feedback WHERE user_id = ?", (uid,))
            cursor.execute("DELETE FROM saved_outfits WHERE user_id = ?", (uid,))
            cursor.execute("DELETE FROM users WHERE id = ?", (uid,))
            
        conn.commit()
        conn.close()

    def test_health_endpoint(self):
        """Test health check route."""
        response = self.app.get('/health')
        self.assertEqual(response.status_code, 200)
        data = json.loads(response.data)
        self.assertEqual(data['status'], 'healthy')

    def test_user_authentication_flow(self):
        """Tests user registration, login, and profile preference updating."""
        # 1. Register User
        reg_payload = {
            "name": "Test Runner",
            "email": self.test_email,
            "password": "securepassword123",
            "age": 25,
            "gender": "Men"
        }
        response = self.app.post('/register', 
                                 data=json.dumps(reg_payload),
                                 content_type='application/json')
        self.assertEqual(response.status_code, 201)
        data = json.loads(response.data)
        self.assertIn('token', data)
        self.assertEqual(data['user']['email'], self.test_email)
        token = data['token']
        headers = {'Authorization': f'Bearer {token}'}

        # 2. Login User
        login_payload = {
            "email": self.test_email,
            "password": "securepassword123"
        }
        response = self.app.post('/login',
                                 data=json.dumps(login_payload),
                                 content_type='application/json')
        self.assertEqual(response.status_code, 200)
        login_data = json.loads(response.data)
        self.assertIn('token', login_data)

        # 3. Retrieve Profile
        response = self.app.get('/profile', headers=headers)
        self.assertEqual(response.status_code, 200)
        profile_data = json.loads(response.data)
        self.assertEqual(profile_data['user']['email'], self.test_email)
        self.assertIn('preferences', profile_data)

        # 4. Update Profile Preferences
        pref_payload = {
            "name": "Test Runner Updated",
            "age": 26,
            "gender": "Men",
            "favorite_colors": ["Black", "Blue"],
            "favorite_styles": ["Streetwear", "Casual"],
            "preferred_fit": "Slim",
            "budget_min": 20.0,
            "budget_max": 250.0
        }
        response = self.app.put('/profile', 
                                data=json.dumps(pref_payload),
                                content_type='application/json',
                                headers=headers)
        self.assertEqual(response.status_code, 200)

        # Re-fetch and check updates
        response = self.app.get('/profile', headers=headers)
        profile_data = json.loads(response.data)
        self.assertEqual(profile_data['user']['name'], "Test Runner Updated")
        self.assertEqual(profile_data['user']['age'], 26)
        self.assertEqual(profile_data['preferences']['preferred_fit'], "Slim")
        self.assertEqual(profile_data['preferences']['favorite_colors'], ["Black", "Blue"])

    def test_recommendation_and_feedback(self):
        """Tests recommendation generation and sending feedback (like/dislike)."""
        # Register a temporary user first
        reg_payload = {"name": "User Recs", "email": self.test_email, "password": "password123", "age": 22, "gender": "Women"}
        response = self.app.post('/register', data=json.dumps(reg_payload), content_type='application/json')
        token = json.loads(response.data)['token']
        headers = {'Authorization': f'Bearer {token}'}

        # 1. Fetch Recommendations
        response = self.app.get('/recommendations?weather=Hot', headers=headers)
        self.assertEqual(response.status_code, 200)
        recs = json.loads(response.data)
        self.assertIsInstance(recs, list)
        
        if len(recs) > 0:
            outfit_id = recs[0]['id']
            
            # 2. Like outfit
            like_res = self.app.post('/like', data=json.dumps({"outfit_id": outfit_id}), content_type='application/json', headers=headers)
            self.assertEqual(like_res.status_code, 200)

            # 3. Dislike outfit
            dislike_res = self.app.post('/dislike', data=json.dumps({"outfit_id": outfit_id}), content_type='application/json', headers=headers)
            self.assertEqual(dislike_res.status_code, 200)

            # 4. Save outfit
            save_res = self.app.post('/save-outfit', data=json.dumps({"outfit_id": outfit_id}), content_type='application/json', headers=headers)
            self.assertEqual(save_res.status_code, 200)

            # 5. Fetch saved outfits
            saved_res = self.app.get('/saved-outfits', headers=headers)
            self.assertEqual(saved_res.status_code, 200)
            saved_list = json.loads(saved_res.data)
            self.assertTrue(any(o['id'] == outfit_id for o in saved_list))

            # 6. Unsave outfit
            unsave_res = self.app.delete(f'/save-outfit/{outfit_id}', headers=headers)
            self.assertEqual(unsave_res.status_code, 200)

    def test_clothing_image_upload_analyzer(self):
        """Test uploading clothing image and triggering CV analysis."""
        # Create a dummy JPEG image in memory for testing upload
        img = Image.new('RGB', (100, 100), color = 'blue')
        img_byte_arr = io.BytesIO()
        img.save(img_byte_arr, format='JPEG')
        img_byte_arr.seek(0)

        # Register user
        reg_payload = {"name": "Upload User", "email": self.test_email, "password": "password123", "age": 28, "gender": "Unisex"}
        response = self.app.post('/register', data=json.dumps(reg_payload), content_type='application/json')
        token = json.loads(response.data)['token']
        headers = {'Authorization': f'Bearer {token}'}

        # Upload clothing
        response = self.app.post('/upload-clothing',
                                 data={'image': (img_byte_arr, 'test_jeans.jpg')},
                                 content_type='multipart/form-data',
                                 headers=headers)
        self.assertEqual(response.status_code, 201)
        data = json.loads(response.data)
        self.assertEqual(data['item']['color'], 'Blue') # Should analyze blue color correctly
        self.assertIn('id', data['item'])

    def test_admin_restrictions_and_analytics(self):
        """Tests that normal users cannot access admin endpoints, but admins can."""
        # 1. Register User (normal role)
        reg_payload = {"name": "Normal User", "email": self.test_email, "password": "password123", "age": 22, "gender": "Women"}
        response = self.app.post('/register', data=json.dumps(reg_payload), content_type='application/json')
        user_token = json.loads(response.data)['token']
        user_headers = {'Authorization': f'Bearer {user_token}'}

        # Check access to admin analytics (should be 403 Forbidden)
        admin_res = self.app.get('/admin/analytics', headers=user_headers)
        self.assertEqual(admin_res.status_code, 403)

        # 2. Register Admin User
        # Workaround: Since registration defaults to 'user' role, we seed/register normally,
        # then toggle their role in database directly for testing.
        admin_reg_payload = {"name": "Admin Tester", "email": self.test_admin_email, "password": "adminpassword", "age": 35, "gender": "Unisex"}
        response = self.app.post('/register', data=json.dumps(admin_reg_payload), content_type='application/json')
        admin_token = json.loads(response.data)['token']
        admin_headers = {'Authorization': f'Bearer {admin_token}'}

        # Promote user to admin in SQLite
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("UPDATE users SET role = 'admin' WHERE email = ?", (self.test_admin_email,))
        conn.commit()
        conn.close()

        # Try to access admin analytics (should now succeed)
        admin_res = self.app.get('/admin/analytics', headers=admin_headers)
        self.assertEqual(admin_res.status_code, 200)
        data = json.loads(admin_res.data)
        self.assertIn('total_users', data)
        self.assertIn('total_outfits', data)

        # CRUD: Get admin users list
        users_res = self.app.get('/admin/users', headers=admin_headers)
        self.assertEqual(users_res.status_code, 200)

if __name__ == '__main__':
    unittest.main()
